node {

    checkout scm
    env.DOCKER_API_VERSION="1.23"

    sh "git rev-parse --short HEAD > commit-id"
    tag = readFile('commit-id').replace("\n", "").replace("\r", "")

    appName = "api-service"
    registryHost = "127.0.0.1:30400/"
    imageName = "${registryHost}${appName}:latest"
    env.BUILDIMG=imageName

stage "Cleanup"



stage "Build"
sh "docker build -t ${imageName} -f kubernetes-go-grpc/api/Dockerfile kubernetes-go-grpc/api"

stage "Push"
    sh "docker push ${imageName}"

stage "Deploy"
kubernetesDeploy configs: "kubernetes-go-grpc/deployment/*.yaml", kubeconfigId: 'kenzan_kubeconfig'
}
    

